server:
 port: 8080
spring:
 h2:
  console:
   enabled: true
   path: /h2-console
 application:
  name: friendsnet
 datasource:
  hikari:
   connection-timeout: 60000
   maximum-pool-size: 5
  url: jdbc:h2:~/db_friendsnet.db;DB_CLOSE_DELAY=1000
  password: a
  username: a
 jpa:
  hibernate:
   ddl-auto: create-drop